/*
 Navicat Premium Dump SQL

 Source Server         : santaadventure
 Source Server Type    : PostgreSQL
 Source Server Version : 150005 (150005)
 Source Host           : 119.28.134.243:5432
 Source Catalog        : santa
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 150005 (150005)
 File Encoding         : 65001

 Date: 08/12/2024 21:11:52
*/


-- ----------------------------
-- Table structure for category
-- ----------------------------
DROP TABLE IF EXISTS "public"."category";
CREATE TABLE "public"."category" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "pid" int4 NOT NULL DEFAULT 0,
  "has_child" bool NOT NULL DEFAULT false,
  "name_ja" varchar(255) COLLATE "pg_catalog"."default",
  "name_de" varchar(255) COLLATE "pg_catalog"."default",
  "name_es" varchar(255) COLLATE "pg_catalog"."default",
  "name_fr" varchar(255) COLLATE "pg_catalog"."default",
  "name_pt" varchar(255) COLLATE "pg_catalog"."default",
  "name_ru" varchar(255) COLLATE "pg_catalog"."default",
  "name_zh" varchar(255) COLLATE "pg_catalog"."default",
  "name_tw" varchar(255) COLLATE "pg_catalog"."default",
  "category_name" varchar(255) COLLATE "pg_catalog"."default",
  "sort" int4 NOT NULL DEFAULT 0,
  "name_ko" varchar(255) COLLATE "pg_catalog"."default",
  "name_it" varchar(255) COLLATE "pg_catalog"."default",
  "name_ar" varchar(255) COLLATE "pg_catalog"."default",
  "name_in" varchar(255) COLLATE "pg_catalog"."default",
  "name_ms" varchar(255) COLLATE "pg_catalog"."default",
  "name_th" varchar(255) COLLATE "pg_catalog"."default",
  "name_vi" varchar(255) COLLATE "pg_catalog"."default",
  "name_tr" varchar(255) COLLATE "pg_catalog"."default",
  "name_pl" varchar(255) COLLATE "pg_catalog"."default",
  "name_nl" varchar(255) COLLATE "pg_catalog"."default",
  "title_ja" text COLLATE "pg_catalog"."default",
  "title_de" text COLLATE "pg_catalog"."default",
  "title_es" text COLLATE "pg_catalog"."default",
  "title_fr" text COLLATE "pg_catalog"."default",
  "title_pt" text COLLATE "pg_catalog"."default",
  "title_ru" text COLLATE "pg_catalog"."default",
  "title_zh" text COLLATE "pg_catalog"."default",
  "title_tw" text COLLATE "pg_catalog"."default",
  "title_ko" text COLLATE "pg_catalog"."default",
  "title_it" text COLLATE "pg_catalog"."default",
  "title_ar" text COLLATE "pg_catalog"."default",
  "title_in" text COLLATE "pg_catalog"."default",
  "title_ms" text COLLATE "pg_catalog"."default",
  "title_th" text COLLATE "pg_catalog"."default",
  "title_vi" text COLLATE "pg_catalog"."default",
  "title_tr" text COLLATE "pg_catalog"."default",
  "title_pl" text COLLATE "pg_catalog"."default",
  "title_nl" text COLLATE "pg_catalog"."default",
  "content" text COLLATE "pg_catalog"."default",
  "content_ja" text COLLATE "pg_catalog"."default",
  "content_de" text COLLATE "pg_catalog"."default",
  "content_es" text COLLATE "pg_catalog"."default",
  "content_fr" text COLLATE "pg_catalog"."default",
  "content_pt" text COLLATE "pg_catalog"."default",
  "content_ru" text COLLATE "pg_catalog"."default",
  "content_zh" text COLLATE "pg_catalog"."default",
  "content_tw" text COLLATE "pg_catalog"."default",
  "content_ko" text COLLATE "pg_catalog"."default",
  "content_it" text COLLATE "pg_catalog"."default",
  "content_ar" text COLLATE "pg_catalog"."default",
  "content_in" text COLLATE "pg_catalog"."default",
  "content_ms" text COLLATE "pg_catalog"."default",
  "content_th" text COLLATE "pg_catalog"."default",
  "content_vi" text COLLATE "pg_catalog"."default",
  "content_tr" text COLLATE "pg_catalog"."default",
  "content_pl" text COLLATE "pg_catalog"."default",
  "content_nl" text COLLATE "pg_catalog"."default",
  "h1" text COLLATE "pg_catalog"."default",
  "h1_ja" text COLLATE "pg_catalog"."default",
  "h1_de" text COLLATE "pg_catalog"."default",
  "h1_es" text COLLATE "pg_catalog"."default",
  "h1_fr" text COLLATE "pg_catalog"."default",
  "h1_pt" text COLLATE "pg_catalog"."default",
  "h1_ru" text COLLATE "pg_catalog"."default",
  "h1_zh" text COLLATE "pg_catalog"."default",
  "h1_tw" text COLLATE "pg_catalog"."default",
  "h1_ko" text COLLATE "pg_catalog"."default",
  "h1_it" text COLLATE "pg_catalog"."default",
  "h1_ar" text COLLATE "pg_catalog"."default",
  "h1_in" text COLLATE "pg_catalog"."default",
  "h1_ms" text COLLATE "pg_catalog"."default",
  "h1_th" text COLLATE "pg_catalog"."default",
  "h1_vi" text COLLATE "pg_catalog"."default",
  "h1_tr" text COLLATE "pg_catalog"."default",
  "h1_pl" text COLLATE "pg_catalog"."default",
  "h1_nl" text COLLATE "pg_catalog"."default",
  "title" text COLLATE "pg_catalog"."default"
)
;
