/*
 Navicat Premium Dump SQL

 Source Server         : santaadventure
 Source Server Type    : PostgreSQL
 Source Server Version : 150005 (150005)
 Source Host           : 119.28.134.243:5432
 Source Catalog        : santa
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 150005 (150005)
 File Encoding         : 65001

 Date: 08/12/2024 21:12:34
*/


-- ----------------------------
-- Table structure for product_tag
-- ----------------------------
DROP TABLE IF EXISTS "public"."product_tag";
CREATE TABLE "public"."product_tag" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "product_id" int8,
  "tag_id" int8
)
;

-- ----------------------------
-- Primary Key structure for table product_tag
-- ----------------------------
ALTER TABLE "public"."product_tag" ADD CONSTRAINT "category_copy1_pkey" PRIMARY KEY ("id");
