/*
 Navicat Premium Dump SQL

 Source Server         : santaadventure
 Source Server Type    : PostgreSQL
 Source Server Version : 150005 (150005)
 Source Host           : 119.28.134.243:5432
 Source Catalog        : santa
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 150005 (150005)
 File Encoding         : 65001

 Date: 08/12/2024 21:12:15
*/


-- ----------------------------
-- Table structure for product_detail
-- ----------------------------
DROP TABLE IF EXISTS "public"."product_detail";
CREATE TABLE "public"."product_detail" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "collection_time" timestamp(6),
  "content" text COLLATE "pg_catalog"."default",
  "detail" text COLLATE "pg_catalog"."default",
  "image_url" text COLLATE "pg_catalog"."default",
  "name" text COLLATE "pg_catalog"."default",
  "star_rating" text COLLATE "pg_catalog"."default",
  "thumbnail_url" text COLLATE "pg_catalog"."default",
  "title" text COLLATE "pg_catalog"."default",
  "url" text COLLATE "pg_catalog"."default",
  "website_data" text COLLATE "pg_catalog"."default",
  "title_ja" text COLLATE "pg_catalog"."default",
  "detail_ja" text COLLATE "pg_catalog"."default",
  "content_ja" text COLLATE "pg_catalog"."default",
  "title_de" text COLLATE "pg_catalog"."default",
  "detail_de" text COLLATE "pg_catalog"."default",
  "content_de" text COLLATE "pg_catalog"."default",
  "title_es" text COLLATE "pg_catalog"."default",
  "detail_es" text COLLATE "pg_catalog"."default",
  "content_es" text COLLATE "pg_catalog"."default",
  "title_fr" text COLLATE "pg_catalog"."default",
  "detail_fr" text COLLATE "pg_catalog"."default",
  "content_fr" text COLLATE "pg_catalog"."default",
  "title_pt" text COLLATE "pg_catalog"."default",
  "detail_pt" text COLLATE "pg_catalog"."default",
  "content_pt" text COLLATE "pg_catalog"."default",
  "title_ru" text COLLATE "pg_catalog"."default",
  "detail_ru" text COLLATE "pg_catalog"."default",
  "content_ru" text COLLATE "pg_catalog"."default",
  "title_zh" text COLLATE "pg_catalog"."default",
  "detail_zh" text COLLATE "pg_catalog"."default",
  "content_zh" text COLLATE "pg_catalog"."default",
  "title_tw" text COLLATE "pg_catalog"."default",
  "detail_tw" text COLLATE "pg_catalog"."default",
  "content_tw" text COLLATE "pg_catalog"."default",
  "price" numeric(10,2),
  "traffic" int8,
  "url_key" varchar(255) COLLATE "pg_catalog"."default",
  "title_ko" text COLLATE "pg_catalog"."default",
  "detail_ko" text COLLATE "pg_catalog"."default",
  "content_ko" text COLLATE "pg_catalog"."default",
  "title_it" text COLLATE "pg_catalog"."default",
  "detail_it" text COLLATE "pg_catalog"."default",
  "content_it" text COLLATE "pg_catalog"."default",
  "title_ar" text COLLATE "pg_catalog"."default",
  "detail_ar" text COLLATE "pg_catalog"."default",
  "content_ar" text COLLATE "pg_catalog"."default",
  "title_in" text COLLATE "pg_catalog"."default",
  "detail_in" text COLLATE "pg_catalog"."default",
  "content_in" text COLLATE "pg_catalog"."default",
  "title_ms" text COLLATE "pg_catalog"."default",
  "detail_ms" text COLLATE "pg_catalog"."default",
  "content_ms" text COLLATE "pg_catalog"."default",
  "title_th" text COLLATE "pg_catalog"."default",
  "detail_th" text COLLATE "pg_catalog"."default",
  "content_th" text COLLATE "pg_catalog"."default",
  "title_vi" text COLLATE "pg_catalog"."default",
  "detail_vi" text COLLATE "pg_catalog"."default",
  "content_vi" text COLLATE "pg_catalog"."default",
  "title_tr" text COLLATE "pg_catalog"."default",
  "detail_tr" text COLLATE "pg_catalog"."default",
  "content_tr" text COLLATE "pg_catalog"."default",
  "title_pl" text COLLATE "pg_catalog"."default",
  "detail_pl" text COLLATE "pg_catalog"."default",
  "content_pl" text COLLATE "pg_catalog"."default",
  "title_nl" text COLLATE "pg_catalog"."default",
  "detail_nl" text COLLATE "pg_catalog"."default",
  "content_nl" text COLLATE "pg_catalog"."default",
  "h1" text COLLATE "pg_catalog"."default",
  "h1_ja" text COLLATE "pg_catalog"."default",
  "h1_de" text COLLATE "pg_catalog"."default",
  "h1_es" text COLLATE "pg_catalog"."default",
  "h1_fr" text COLLATE "pg_catalog"."default",
  "h1_pt" text COLLATE "pg_catalog"."default",
  "h1_ru" text COLLATE "pg_catalog"."default",
  "h1_zh" text COLLATE "pg_catalog"."default",
  "h1_tw" text COLLATE "pg_catalog"."default",
  "h1_ko" text COLLATE "pg_catalog"."default",
  "h1_it" text COLLATE "pg_catalog"."default",
  "h1_ar" text COLLATE "pg_catalog"."default",
  "h1_in" text COLLATE "pg_catalog"."default",
  "h1_ms" text COLLATE "pg_catalog"."default",
  "h1_th" text COLLATE "pg_catalog"."default",
  "h1_vi" text COLLATE "pg_catalog"."default",
  "h1_tr" text COLLATE "pg_catalog"."default",
  "h1_pl" text COLLATE "pg_catalog"."default",
  "h1_nl" text COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "public"."product_detail"."url_key" IS '从url变换得到的唯一值';
COMMENT ON TABLE "public"."product_detail" IS 'product details';
